stages:
  data_ingestion:
    cmd: python src/pcpartsclassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/pcpartsclassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion

  base_model:
    cmd: python src/pcpartsclassifier/pipeline/stage_02_base_model.py
    deps:
      - src/pcpartsclassifier/pipeline/stage_02_base_model.py
      - config/config.yaml
    params:
      - DATA_NAME
      - CLASSES
    outs:
      - artifacts/base_model

  training:
    cmd: python src/pcpartsclassifier/pipeline/stage_03_model_trainer.py
    deps:
      - src/pcpartsclassifier/pipeline/stage_03_model_trainer.py
      - config/config.yaml
      - artifacts/data_ingestion/pc_parts
    params:
      - DATA_NAME
      - BATCH_SIZE
      - LEARNING_RATE
      - EPOCHS
    outs:
      - artifacts/training/trained_model.pth

  evaluation:
    cmd: python src/pcpartsclassifier/pipeline/stage_04_model_evaluation.py
    deps:
      - src/pcpartsclassifier/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/pc_parts
      - artifacts/training/trained_model.pth
    params:
      - DATA_NAME
      - BATCH_SIZE
    metrics:
      - scores.json:
          cache: false
